### ISSUE TITLE
照着运行出错

### ISSUE THREAD

**Issue by Qinneys** [alipay/Ant-Multi-Modal-Framework#27]
python run.py 

Downloading: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    encoder.warmup_local_model()
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/nn4k/invoker/base.py", line 190, in warmup_local_model
    self._nn_executor.load_model()
  File "/data/workspace/Ant-Multi-Modal-Framework/prj/M2_Encoder/m2_encoder.py", line 28, in load_model
    model, processors = load_from_config(model_config)
  File "/data/workspace/Ant-Multi-Modal-Framework/prj/M2_Encoder/vlmo/utils/beit_utils.py", line 58, in load_from_config
    model_dir = snapshot_download(**modelscope_cfg)
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 84, in snapshot_download
    return _snapshot_download(
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 241, in _snapshot_download
    _download_file_lists(
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 416, in _download_file_lists
    download_file(url, repo_file, temporary_cache_dir, cache, headers,
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 606, in download_file
    file_integrity_validation(temp_file, file_meta[FILE_HASH])
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/utils/utils.py", line 88, in file_integrity_validation
    file_sha256 = compute_hash(file_path)
  File "/root/miniconda3/envs/torch200/lib/python3.8/site-packages/modelscope/hub/utils/utils.py", line 68, in compute_hash
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/modelscope/hub/._____temp/M2Cognition/M2-Encoder/vlmo/__init__.py'

**Comment by Qinneys** [comment]
modelscope版本问题，将1.17.1降为1.16后解决
